survey_prompt = "Ready to talk about when we should meet to discuss Short Message LLC? Please respond with 'y' or 'yes' when you are ready to begin."
sorry_message = "If you have any issues with the survey, please contact us at shortmessagesurvey@gmail.com."
time_expired  = "The time to complete the survey has expired"
welcome_text  = "Please respond to the following items about your availability with 'yes' or 'no'"   
phone_number = "+18652639199"
time_limit = 300
controller_message = "Hi would you like to trigger a survey or would you like to check the status. Reply 1 to check the status, 2 to trigger a survey."
survey_file = "branch_survey.json"